from functions.generic_functions_modules import *

def aboutus_aboutus_body_validation(driver):
    print('verifying aboutus_Body containers')
    time.sleep(3)
    WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID, "title-2461")))
    herocontent = driver.find_element_by_xpath("//div[contains(@class, 'hero__content hero__content-align-center')]")
    print(herocontent.text)
    herosubcontent = driver.find_element_by_xpath("//div[contains(@class, 'hero__tout hero__tout--blue')]")
    print(herosubcontent.text)
    wehavejewelryinourname = driver.find_element_by_xpath("//div[contains(@class, 'layout layout--twocol-section layout--twocol-section--50-50')]")
    print(wehavejewelryinourname.text)
    wehavejewelryvideomodal = driver.find_element_by_id('video-modal-6136').is_displayed()
    print(wehavejewelryvideomodal, "Video modal is displayed")
    partnerships = driver.find_element_by_id('title-2461')
    print(partnerships.text)
    partershipsinfogrid = driver.find_element_by_id('info-grid-2506')
    print(partershipsinfogrid.text)
    givingbackbrilliantly = driver.find_element_by_id('feature-row-2511')
    print(givingbackbrilliantly.text)
    leadership = driver.find_element_by_id('title-2516')
    print(leadership.text)
    executiveofficers = driver.find_element_by_id('text-block-2526')
    print(executiveofficers.text)
    executiveofficersinfogrid = driver.find_element_by_id('info-grid-2566')
    print(executiveofficersinfogrid.text)
#    businessleaders = driver.find_element_by_id('text-block-2576')
#    print(businessleaders.text)
#    businessleadersinfogrid = driver.find_element_by_id('info-grid-2626')
#    print(businessleadersinfogrid.text)
    ourboardofdirectors = driver.find_element_by_id('text-block-2636')
    print(ourboardofdirectors.text)
    ourboardofdirectorsinforid = driver.find_element_by_id('info-grid-2696')
    print(ourboardofdirectorsinforid.text)
    alittlemoreaboutus = driver.find_element_by_id('title-2701')
    print(alittlemoreaboutus.text)
    whatsinaname = driver.find_element_by_id('text-image-row-2706')
    print(whatsinaname.text)
    whatsinanameimage = driver.find_element_by_xpath('//img[@alt="storefront illustration"]').is_displayed()
    print(whatsinanameimage, "Image is displayed")
    welovejewelry = driver.find_element_by_id('text-image-row-2711')
    print(welovejewelry.text)
    welovejewelryimage = driver.find_element_by_xpath('//img[@alt="jeweler\'s workstation illustration"]').is_displayed()
    print(welovejewelryimage, "Image is displayed")
    lovejewelrytoo = driver.find_element_by_id('text-image-row-2716')
    print(lovejewelrytoo.text)
    trustpilotblock = driver.find_element_by_id('basic-code-block-trustpilot-about-us-horizontal')
    print(trustpilotblock.text)
    element = driver.find_element_by_id('text-image-row-2716')
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    time.sleep(3)
    print('aboutus_Body - verified')
    return True
def aboutus_socialresponsibility_body_validation(driver):
    print('verifying socialresponsibility_Body containers')
    time.sleep(3)
    WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID, "title-5316")))
    heroContent = driver.find_element_by_xpath("//div[contains(@class, 'hero__image-container hero__image-container--no-mobile-image')]")
    print(heroContent.text)
    bandTogetherCampaign = driver.find_element_by_id('title-5316')
    print(bandTogetherCampaign.text)
    bandTogetherInfogrid = driver.find_element_by_id('info-grid-5311')
    print(bandTogetherInfogrid.text)
    kidsInNeedImage = driver.find_element_by_xpath('//img[@alt="Kids in Need Foundation"]').is_displayed()
    print(kidsInNeedImage, "Kids in Need Foundation image is displayed.")
    feedingAmerica = driver.find_element_by_xpath('//img[@alt="Feeding America"]').is_displayed()
    print(feedingAmerica, "Feeding America image is displayed.")
    standUpToCancerImage = driver.find_element_by_xpath('//img[@alt="Stand Up To Cancer"]').is_displayed()
    print(standUpToCancerImage, "Stand Up To Cancer image is displayed.")
    supplyATeacher = driver.find_element_by_xpath("//div[contains(@class, 'layout layout--twocol-section layout--twocol-section--50-50')]")
    print(supplyATeacher.text)
    supplyATeacherImage = driver.find_element_by_xpath('//img[@alt="Supply a Teacher"]').is_displayed()
    print(supplyATeacherImage, "Supply a Teacher image is displayed.")
    strengtheningTheJewelryIndustry = driver.find_element_by_id('text-image-row-2361')
    print(strengtheningTheJewelryIndustry .text)
    strengtheningImage = driver.find_element_by_xpath('//img[@alt="diamond heart illustration"]').is_displayed()
    print(strengtheningImage, "Strengthening the Jewelry Industry image is displayed.")
    helpingOurEmployeesHelpOthers = driver.find_element_by_id('title-2366')
    print(helpingOurEmployeesHelpOthers.text)
    helpingInfogrid = driver.find_element_by_id('info-grid-2391')
    print(helpingInfogrid .text)
    #ICONS
    learnMoreAboutUs = driver.find_element_by_id('feature-row-2411')
    print(learnMoreAboutUs.text)
    element = driver.find_element_by_id('feature-row-2411')
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    time.sleep(3)
    print('socialresponsibility_Body - verified')
    return True
def aboutus_careers_body_validation(driver):
    print('verifying careers_Body containers')
    time.sleep(3)
    WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID, "info-grid-1736")))
    # heroContent = driver.find_element_by_xpath("//div[contains(@class, 'hero__content hero__content-align-center')]")
    # print(heroContent.text)
    # ourPeopleAreOurGreatestAssetTitle = driver.find_element_by_id('feature-row-1716')
    # print(ourPeopleAreOurGreatestAssetTitle.text)
    ourPeopleAreOurGreatestAssetInfogrid = driver.find_element_by_id('info-grid-1736')
    print(ourPeopleAreOurGreatestAssetInfogrid.text)
    officeCaroussel = driver.find_element_by_id('carousel-1776').is_displayed()
    print(officeCaroussel, "Office caroussel is displayed.")
    # ourBenefits = driver.find_element_by_id('feature-row-1781')
    # print(ourBenefits.text)
    # ourBenefitsIcon = driver.find_element_by_xpath('//img[@alt="diamond"]').is_displayed()
    # print(ourBenefitsIcon, "Our Benefits icon is displayed.")
    benefits = driver.find_element_by_id('tab-section-4286')
    print(benefits.text)
#    ourAwards = driver.find_element_by_id('feature-row-8151')
#    print(ourAwards.text)
    ourAwardsInfogrid = driver.find_element_by_id('info-grid-8146')
    print(ourAwardsInfogrid.text)
    testimonialCaroussel = driver.find_element_by_id('carousel-1946').is_displayed()
    print(testimonialCaroussel, "Testimonial caroussel is displayed.")
#    hiringProcess = driver.find_element_by_id('feature-row-1816')
#   print(hiringProcess.text)
    hiringProcessTabs = driver.find_element_by_id('tab-section-4311')
    print(hiringProcessTabs.text)
#    ourLocations = driver.find_element_by_id('feature-row-4801')
#    print(ourLocations.text)
#    eVerify = driver.find_element_by_id('feature-row-4796')
#    print(eVerify.text)
    contact = driver.find_element_by_id('contact-ribbon-1876')
    print(contact.text)
    talkToUsForm = driver.find_element_by_css_selector('form[class*=contact-form]').is_displayed()
    print(talkToUsForm, "Talk to us form is displayed.")
    map = driver.find_element_by_id('basic-code-block-google-map').is_displayed()
    print(map, "Map is displayed.")
    element = driver.find_element_by_id('basic-code-block-google-map')
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    time.sleep(3)
    print('careers_Body - verified')
    return True
def aboutus_newsroom_body_validation(driver):
    print('verifying newsroom_Body containers')
    time.sleep(3)
    WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID, "block-newsheroblock")))
    herocontent = driver.find_element_by_id('block-newsheroblock')
    print(herocontent.text)
    newsroomContent = driver.find_element_by_id('block-jewelers-mutual-content')
    print(newsroomContent.text)
    element = driver.find_element_by_id('text-block-8926')
    actions = ActionChains(driver)
    actions.move_to_element(element).perform()
    time.sleep(3)
    print('newsroom_Body - verified')
    return True